add option: rgb bum

diff --git a/bin/pironman5 b/bin/pironman5
--- a/bin/pironman5
+++ b/bin/pironman5
@@ -21,9 +21,11 @@
 ####
 ####   -u,--unit            [ C/F ], set the unit of temperature,
 ####                        C or F (Celsius/Fahrenheit)
+####  
+####   -re|--rgb_enable    [on/true/off/false], whether enable rgb strip,
 ####
-####   -re|--rgb_enable)    [on/true/off/false], whether enable rgb strip,
-####
+####   -rn|--rgb_num        the number of rgb lamp beads, default 4
+#### 
 ####   -rs,--rgb_style      rgb strip display style, default: breath,
 ####                        in [breath / leap / flow / raise_up / colorful]
 ####
@@ -218,6 +220,26 @@ while [[ $# -gt 0 ]]; do
           exit 1
         ;;
       esac
+      ;;
+    -rn|--rgb_num)
+      if [ $# -lt 2 ]; then
+        echo "usage: pironman5  -rn|--rgb_num [number]"
+        exit 1
+      else
+        if [[ $2 =~ ^[[:digit:]]+$ ]]; then
+          if [ $2 -ge 0 ]; then
+            echo "set rgb_num to $2 "
+            sed -i -e "s:rgb_num.*=.*:rgb_num = $2:g" ${CONF}
+            shift 2
+          else
+            echo "invalid value"
+            exit 1
+          fi
+        else
+          echo "parameter must be integer"
+          exit 1
+        fi
+      fi
       ;;
     -rs|--rgb_style)
       case "$2" in
